### ISSUE TITLE
IETF 120 - Who can mint a Glue ID

### ISSUE THREAD

**Issue by pamelatech** [mesur-io/draft-zundel-spice-glue-id#10]
Questions from IETF 120 Plenary Vancouver (https://notes.ietf.org/notes-ietf-120-spice)

AJ Stein: Can arbitrary organizations mint these identifiers?
The registry aims to include well-known organizations that identify businesses, but flexibility allows for new authorities to be recognized based on trust and context.

**Comment by brentzundel** [comment]
We need to update the abstract to say that GLUE IDs are a representation format for existing issued identifiers.
