### ISSUE TITLE
IETF 120 - Should Glue IDs be in SPICE?

### ISSUE THREAD

**Issue by pamelatech** [mesur-io/draft-zundel-spice-glue-id#11]
Questions taken from IETF 120 Plenary Vancouver (https://notes.ietf.org/notes-ietf-120-spice)

Heather Flanagan (chair) : How does this fit within SPICE?
The Glue ID provides a unified way to refer to companies, aligning with SPICE’s goal of managing credentials and attestations about entities.

**Comment by brentzundel** [comment]
@pamelatech the introduction already has the text
```
Enterprise entity identifiers are myriad. With the increasing use of digitial
credentials, there is a need for a common methodology for expressing these
identifiers such that claims about and by such entities can be made in a
consistent and interoperable manner.
```

do we need more than this for the spec to belong in SPICE?

**Comment by pamelatech** [comment]
Let's leave it and see if others indicate confusion.
