### ISSUE TITLE
IETF120 - Why is an IANA PEN not sufficient?

### ISSUE THREAD

**Issue by pamelatech** [mesur-io/draft-zundel-spice-glue-id#6]
Question #1 from IETF 120 - copied from session notes (https://notes.ietf.org/notes-ietf-120-spice)

AJ Stein: Why are existing identifiers like IANA’s PENs not sufficient?
- Roy Williams: the scope of identifiers needs to cover a wide range of entities, including those without U.S. entities or computers. The scheme needs to allow flexibility worldwide.
AJ (Follow-up): If this requires registration with IANA, that might be a problem.
- The Glue ID aims to provide a flexible and widely applicable solution, recognizing different authorities and their specific needs.

**Comment by brentzundel** [comment]
GLUE ID is a common representation of issued identifiers, it is not of itself an issued identifier.

We should include PEN identifier examples and make sure they are a registered in the GLUE ID Registry

**Comment by brentzundel** [comment]
Also, registration of the authority schemes shouldn't need to be done by the authorities themselves. Anyone who can point to the scheme and how to resolve could register it.
